export const LOADING = 'LOADING';
export const GET_APP_STATE = 'GET_APP_STATE';
export const GET_APP_STATE_FAILED = 'GET_APP_STATE_FAILED';
export const CREATE_APP_STATE = 'CREATE_APP_STATE';
export const CREATE_APP_STATE_FAILED = 'CREATE_APP_STATE_FAILED';
