export const SEARCH_DONNER_SUCCESS = 'SEARCH_DONNER_SUCCESS';
export const SEARCH_DONNER_FAILED = 'SEARCH_DONNER_FAILED';
export const SEARCH_CAR = 'SEARCH_CAR';
export const SEARCH_LOADING = 'SEARCH_LOADING';